<li class="nav-item seccion seccion[idSeccion]">
    <a class="nav-link [classSeccion] text-white" data-seccion="[seccion]">
        <div style="pointer-events: none;" class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="fas [iconSeccion]"></i>
        </div>
        <span class="nav-link-text font-weight-normal ms-1" style="pointer-events: none;">[labelSeccion]</span>
    </a>
</li>